import React, { useState } from 'react';
import { motion } from 'framer-motion';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  LineChart, Line, AreaChart, Area, PieChart, Pie, Cell, Legend
} from 'recharts';
import { BarChart3, TrendingUp, Filter, PieChart as PieIcon, Zap, Users, ArrowUpRight } from 'lucide-react';
import {
  REVENUE_BY_CAMPAIGN, MONTHLY_SPEND_VS_REVENUE, CONVERSION_FUNNEL_DATA,
  CUSTOMER_SEGMENTS
} from '../../mock/marketingData';

export const AnalyticsChartsGrid = () => {
  const [activeChartTab, setActiveChartTab] = useState('revenue_spend');

  return (
    <div className="space-y-6">
      {/* Chart Section Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-100 flex items-center gap-2">
            <BarChart3 className="w-5 h-5 text-indigo-400" /> Enterprise Analytics & Predictive Charts
          </h2>
          <p className="text-xs text-slate-400">Deep-dive visual analytics for revenue attribution, conversion funnels, spend ratios, and campaign ROI.</p>
        </div>

        {/* Tab selector */}
        <div className="flex items-center gap-1 bg-slate-900/80 p-1 rounded-xl border border-slate-700/70 text-xs">
          <button
            onClick={() => setActiveChartTab('revenue_spend')}
            className={`px-3 py-1.5 rounded-lg font-medium transition-all ${
              activeChartTab === 'revenue_spend'
                ? 'bg-indigo-600 text-white shadow-md'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            Revenue & Spend
          </button>
          <button
            onClick={() => setActiveChartTab('funnel_retention')}
            className={`px-3 py-1.5 rounded-lg font-medium transition-all ${
              activeChartTab === 'funnel_retention'
                ? 'bg-indigo-600 text-white shadow-md'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            Conversion Funnel
          </button>
          <button
            onClick={() => setActiveChartTab('segmentation')}
            className={`px-3 py-1.5 rounded-lg font-medium transition-all ${
              activeChartTab === 'segmentation'
                ? 'bg-indigo-600 text-white shadow-md'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            Customer Segments
          </button>
        </div>
      </div>

      {/* Grid of Charts */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        
        {/* Chart 1: Revenue by Campaign */}
        <motion.div
          initial={{ opacity: 0, scale: 0.98 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.3 }}
          className="glass-card rounded-xl p-5 border border-slate-700/60 shadow-xl space-y-4"
        >
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-sm font-bold text-slate-100 flex items-center gap-2">
                <TrendingUp className="w-4 h-4 text-emerald-400" /> Gross Revenue Generated by Campaign (₹ Lakhs)
              </h3>
              <p className="text-[11px] text-slate-400">Direct top-line revenue comparison across active campaigns.</p>
            </div>
            <span className="text-[11px] font-semibold text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/20">
              Top: Monsoon BOGO (₹31.2L)
            </span>
          </div>

          <div className="h-64 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={REVENUE_BY_CAMPAIGN} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#334155" opacity={0.5} />
                <XAxis dataKey="campaign" stroke="#94a3b8" tick={{ fontSize: 11 }} />
                <YAxis stroke="#94a3b8" tick={{ fontSize: 11 }} />
                <Tooltip
                  formatter={(val) => [`₹${val} Lakhs`, 'Revenue']}
                  contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155' }}
                />
                <Bar dataKey="revenue" fill="#6366f1" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </motion.div>

        {/* Chart 2: Monthly Marketing Spend vs Revenue */}
        <motion.div
          initial={{ opacity: 0, scale: 0.98 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.3, delay: 0.1 }}
          className="glass-card rounded-xl p-5 border border-slate-700/60 shadow-xl space-y-4"
        >
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-sm font-bold text-slate-100 flex items-center gap-2">
                <Zap className="w-4 h-4 text-indigo-400" /> Monthly Spend vs Gross Revenue Trend (₹ Lakhs)
              </h3>
              <p className="text-[11px] text-slate-400">6-month marketing expenditure efficiency trajectory.</p>
            </div>
            <span className="text-[11px] font-semibold text-indigo-400 bg-indigo-500/10 px-2 py-0.5 rounded border border-indigo-500/20">
              Avg ROI: 4.85x
            </span>
          </div>

          <div className="h-64 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={MONTHLY_SPEND_VS_REVENUE} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <defs>
                  <linearGradient id="colorRev" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#10b981" stopOpacity={0.4}/>
                    <stop offset="95%" stopColor="#10b981" stopOpacity={0}/>
                  </linearGradient>
                  <linearGradient id="colorSpend" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#6366f1" stopOpacity={0.4}/>
                    <stop offset="95%" stopColor="#6366f1" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#334155" opacity={0.5} />
                <XAxis dataKey="month" stroke="#94a3b8" tick={{ fontSize: 11 }} />
                <YAxis stroke="#94a3b8" tick={{ fontSize: 11 }} />
                <Tooltip
                  formatter={(val, name) => [`₹${val} Lakhs`, name === 'revenue' ? 'Gross Revenue' : 'Ad Spend']}
                  contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155' }}
                />
                <Area type="monotone" dataKey="revenue" stroke="#10b981" fillOpacity={1} fill="url(#colorRev)" strokeWidth={2} />
                <Area type="monotone" dataKey="spend" stroke="#6366f1" fillOpacity={1} fill="url(#colorSpend)" strokeWidth={2} />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </motion.div>

        {/* Chart 3: Conversion Funnel Analysis */}
        <motion.div
          initial={{ opacity: 0, scale: 0.98 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.3, delay: 0.2 }}
          className="glass-card rounded-xl p-5 border border-slate-700/60 shadow-xl space-y-4"
        >
          <div>
            <h3 className="text-sm font-bold text-slate-100 flex items-center gap-2">
              <Filter className="w-4 h-4 text-cyan-400" /> Full-Funnel Customer Acquisition Conversion
            </h3>
            <p className="text-[11px] text-slate-400">Step-by-step visitor progression from ad impressions to checkout completion.</p>
          </div>

          <div className="space-y-3 pt-2">
            {CONVERSION_FUNNEL_DATA.map((stage, i) => (
              <div key={stage.stage} className="space-y-1">
                <div className="flex justify-between text-xs font-semibold">
                  <span className="text-slate-300">{stage.stage}</span>
                  <span className="text-slate-400">{stage.count.toLocaleString()} ({stage.percentage})</span>
                </div>
                <div className="w-full h-3.5 bg-slate-900/90 rounded-full overflow-hidden p-0.5 border border-slate-700/50">
                  <div
                    className="h-full rounded-full transition-all duration-500"
                    style={{
                      width: `${100 - i * 18}%`,
                      backgroundColor: stage.fill
                    }}
                  />
                </div>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Chart 4: Customer Segmentation Distribution */}
        <motion.div
          initial={{ opacity: 0, scale: 0.98 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.3, delay: 0.3 }}
          className="glass-card rounded-xl p-5 border border-slate-700/60 shadow-xl space-y-4"
        >
          <div>
            <h3 className="text-sm font-bold text-slate-100 flex items-center gap-2">
              <PieIcon className="w-4 h-4 text-purple-400" /> AI Customer Cohort & Segmentation Breakdown
            </h3>
            <p className="text-[11px] text-slate-400">Audience distribution by spending power, frequency, and churn risk.</p>
          </div>

          <div className="flex flex-col sm:flex-row items-center gap-4">
            <div className="h-56 w-full sm:w-1/2">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={CUSTOMER_SEGMENTS}
                    cx="50%"
                    cy="50%"
                    innerRadius={50}
                    outerRadius={80}
                    paddingAngle={4}
                    dataKey="percentage"
                  >
                    {CUSTOMER_SEGMENTS.map((entry) => (
                      <Cell key={entry.name} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip
                    formatter={(val) => [`${val}%`, 'Audience Share']}
                    contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155' }}
                  />
                </PieChart>
              </ResponsiveContainer>
            </div>

            <div className="w-full sm:w-1/2 space-y-2">
              {CUSTOMER_SEGMENTS.map((seg) => (
                <div key={seg.name} className="flex items-center justify-between text-xs">
                  <div className="flex items-center gap-2">
                    <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: seg.color }} />
                    <span className="text-slate-300 font-medium">{seg.name}</span>
                  </div>
                  <span className="text-slate-400 font-semibold">{seg.percentage}%</span>
                </div>
              ))}
            </div>
          </div>
        </motion.div>

      </div>
    </div>
  );
};
